# main_prune_runner.py
import json
from pruning.pruning_pipeline import run_pruning_pipeline


if __name__ == "__main__":

    # Load folder structure
    with open("data/folder_structure.json", "r", encoding="utf-8") as f:
        folder_tree = json.load(f)

    # Load stack meta (generated by main_runner)
    with open("data/stack_meta.json", "r", encoding="utf-8") as f:
        meta = json.load(f)

    user_requirement = meta["user_initial_prompt"]
    tech_stack_summary = meta["tech_stack_summary"]

    print("\n=== STARTING PRUNING PHASE ===")
    print("User Requirement:", user_requirement)
    print("Tech Stack:", tech_stack_summary)

    pruned_tree, decisions = run_pruning_pipeline(
        folder_tree,
        user_requirement,
        tech_stack_summary
    )

    # Save pruned structure
    with open("data/pruned_structure.json", "w", encoding="utf-8") as f:
        json.dump(pruned_tree, f, indent=2)

    print("\nPruning complete.")
    print("Pruned structure saved to data/pruned_structure.json")
